name: Deploy Job

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest

    container:
      image: ubuntu:22.04

    timeout-minutes: 60

    env:
      APP_NAME: demo-app

    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: test
          path: .

      - run: echo "Deploying Application..."

      - run: cat test.txt

      - run: echo "Deployment Successful!"
